services:
  poradevapi:
    container_name: poradevapi
    image: laravel_frankenphp
    build: .
    ports:
      - 8000:80
    env_file:
      - .env
    networks:
      custom_network:
        ipv4_address: 172.17.0.2

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16
